import type { ActivityTimelineItem } from "../design-system/components/ActivityTimeline"
import type { CaseRecord } from "../cases/record/types"

export const INITIAL_CASE_RECORD: CaseRecord = {
  title: "Finance team still cannot access the invoice portal after password resets",
  id: "CASE-10482",
  status: "In progress",
  state: "Waiting on customer",
  blockingReason: "awaiting_customer_validation",
  priority: "High",
  assignee: "Lucia Fernandez",
  queue: "Billing Portal Support",
  statusReason: "Awaiting customer confirmation after account remediation.",
  onHoldUntil: "2026-04-02",
  channel: "Email",
  severity: "Major",
  productArea: "Billing Portal",
  category: "Access & Authentication / Multi-factor Access Recovery",
  region: "Southern Europe",
  source: "Customer Support Mailbox",
  timelinePolicy: "Enterprise Plus - Standard Incident",
  responseTarget: "2026-04-01 10:15 CET",
  resolutionTarget: "2026-04-02 17:00 CET",
  firstResponse: "2026-04-01 09:07 CET",
  lastUpdate: "2026-04-01 09:41 CET",
  slaStatus: "At risk",
  breachRisk: "Medium",
  customer: "Viva la Vita Clinics SL",
  contact: "Marta Ruiz",
  email: "marta@vivalavita.com",
  accountTier: "Enterprise Plus",
  contractType: "Enterprise subscription with 24/7 support addendum",
  routingGroup: "Portal Access Recovery",
  approvalRequired: "No",
  approvalReason: "",
  description:
    "Customer reset password twice and still cannot access the billing portal. Recent routing notes suggest a tenant-state mismatch between identity services and the billing portal.",
  internalNotes:
    "Coordinate with IAM before asking the customer to retry. Preserve the current session logs and confirm whether the issue affects all finance users in the clinic group.",
  emailThreadId: "THR-884291",
  callReference: "CALL-2026-04-01-1184",
  chatSessionId: "CHAT-SES-440218",
}

export const EXAMPLE_CASES: CaseRecord[] = [
  INITIAL_CASE_RECORD,
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10463",
    title: "Duplicate payment confirmations are making some invoices look paid twice",
    status: "In progress",
    state: "In investigation",
    blockingReason: "none",
    priority: "Critical",
    assignee: "Jonas Weber",
    queue: "Billing Operations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Critical",
    productArea: "Payments Reconciliation",
    category: "Transactions / Duplicate confirmation records",
    region: "Central Europe",
    source: "Customer Self-Service Portal",
    responseTarget: "2026-04-01 09:15 CET",
    resolutionTarget: "2026-04-01 13:00 CET",
    firstResponse: "2026-04-01 08:55 CET",
    lastUpdate: "2026-04-01 11:22 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Nordstern Dental Group",
    contact: "Eva Kruger",
    email: "eva.kruger@nordstern.example",
    accountTier: "Enterprise",
    contractType: "Enterprise subscription",
    routingGroup: "Payments Reconciliation",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer reports duplicate payment confirmation emails and mismatched invoice statuses after a batch of portal-submitted payments.",
    internalNotes:
      "Cross-check payment gateway webhooks against billing reconciliation logs before reprocessing any invoices.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10511",
    title: "Merged clinic invoices stay missing in the portal until the nightly sync completes",
    status: "In progress",
    state: "Waiting for internal review",
    blockingReason: "awaiting_engineering_fix",
    priority: "High",
    assignee: "Marco Silva",
    queue: "Billing Integrations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Major",
    productArea: "Tenant Data Sync",
    category: "Visibility & Permissions / Post-migration propagation",
    region: "Central Europe",
    source: "Customer Self-Service Portal",
    timelinePolicy: "Enterprise Plus - Standard Incident",
    responseTarget: "2026-04-01 11:00 CET",
    resolutionTarget: "2026-04-02 15:00 CET",
    firstResponse: "2026-04-01 10:05 CET",
    lastUpdate: "2026-04-01 12:06 CET",
    slaStatus: "At risk",
    breachRisk: "Medium",
    customer: "Clinica Sorella",
    contact: "Paolo Vitale",
    email: "paolo.vitale@clinicasorella.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Billing Integrations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Merged clinic invoices are not visible until the nightly tenant sync completes, leaving finance teams with partial invoice views throughout the day.",
    internalNotes:
      "Platform engineering is preparing a sync repair for the tenant-state propagation job. Keep the customer updated while the internal fix is in progress.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10504",
    title: "Finance admins can only see a partial invoice list after the tenant migration",
    status: "In progress",
    state: "Escalated",
    blockingReason: "none",
    priority: "High",
    assignee: "Amelie Laurent",
    queue: "Platform Escalations",
    statusReason: "Escalated to platform engineering after tenant migration logs showed inconsistent visibility scopes.",
    onHoldUntil: "",
    channel: "Phone",
    severity: "Major",
    productArea: "Tenant Administration",
    category: "Visibility & Permissions / Cross-entity access",
    region: "North America",
    source: "Executive escalation hotline",
    timelinePolicy: "Enterprise Plus - Executive Escalation",
    responseTarget: "2026-04-01 10:00 CET",
    resolutionTarget: "2026-04-02 12:00 CET",
    firstResponse: "2026-04-01 09:26 CET",
    lastUpdate: "2026-04-01 12:34 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Northlake Medical Network",
    contact: "Sofia Bennett",
    email: "sofia.bennett@northlake.example",
    accountTier: "Enterprise Plus",
    contractType: "Enterprise subscription with executive escalation coverage",
    routingGroup: "Platform Escalations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Finance admins from merged entities can see only a partial subset of invoices after a tenant migration and permissions sync.",
    internalNotes:
      "Keep the rollback window open until visibility results are confirmed across all merged entities.",
    emailThreadId: "",
    callReference: "CALL-2026-04-01-1219",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10388",
    title: "Can VAT labels be renamed in invoice exports?",
    status: "New",
    state: "Waiting for first response",
    blockingReason: "",
    priority: "",
    assignee: "Anais Martin",
    queue: "General Support",
    statusReason: "",
    onHoldUntil: "",
    channel: "Chat",
    severity: "Minor",
    productArea: "Invoice Export",
    category: "Configuration / Tax labels",
    region: "Latin America",
    source: "Live chat",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-01 15:00 CET",
    resolutionTarget: "2026-04-03 17:00 CET",
    firstResponse: "",
    lastUpdate: "2026-04-01 14:16 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Vida Clara Centro Medico",
    contact: "Ana Perez",
    email: "ana.perez@vidaclara.example",
    accountTier: "Standard",
    contractType: "Standard monthly plan",
    routingGroup: "General Support",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer wants to understand whether VAT labels in exported invoices can be renamed for a local market workflow.",
    internalNotes:
      "Need to confirm whether VAT labels are configurable per export template or only at account level before sending the first response.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "CHAT-SES-440901",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10412",
    title: "Finance users lost billing portal access at one clinic",
    status: "Resolved",
    state: "",
    blockingReason: "none",
    priority: "Medium",
    assignee: "Chiara Marino",
    queue: "Customer Operations",
    statusReason: "Customer confirmed closure after receiving the written resolution summary.",
    onHoldUntil: "",
    channel: "Email",
    severity: "Minor",
    productArea: "Billing Portal",
    category: "Access & Authentication / Portal access restoration",
    region: "Southern Europe",
    source: "Customer Support Mailbox",
    timelinePolicy: "Enterprise Standard",
    responseTarget: "2026-03-31 14:00 CET",
    resolutionTarget: "2026-04-01 17:00 CET",
    firstResponse: "2026-03-31 13:42 CET",
    lastUpdate: "2026-04-02 10:14 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Clinica Sorella",
    contact: "Paolo Vitale",
    email: "paolo.vitale@clinicasorella.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Customer Operations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Finance users lost access to the billing portal until the account-state issue was repaired. The customer later requested a written resolution summary for their records.",
    internalNotes:
      "Keep the IAM repair reference and written resolution summary linked in the record in case the clinic asks for the incident trail again.",
    emailThreadId: "THR-884140",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10516",
    title: "Low-volume clinic adjustments are missing from the daily settlement export",
    status: "In progress",
    state: "In investigation",
    blockingReason: "none",
    priority: "Low",
    assignee: "Nadia Romero",
    queue: "Finance Integrations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Email",
    severity: "Minor",
    productArea: "Settlement Export",
    category: "Reporting / Adjustment visibility",
    region: "Southern Europe",
    source: "Customer Support Mailbox",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-10 11:30 CET",
    resolutionTarget: "2026-04-11 18:00 CET",
    firstResponse: "2026-04-10 11:04 CET",
    lastUpdate: "2026-04-11 08:27 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Clinica Mar Azul",
    contact: "Irene Costa",
    email: "irene.costa@marazul.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Finance Integrations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "The settlement export omits low-volume adjustment rows for a subset of clinic entities, forcing the finance team to reconcile them manually.",
    internalNotes:
      "Initial analysis suggests the export job is skipping adjustments that are posted after the batch window but before summary generation.",
    emailThreadId: "THR-884514",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10518",
    title: "Can overdue invoice reminders be delayed by two business days?",
    status: "New",
    state: "Needs assignment",
    blockingReason: "",
    priority: "Medium",
    assignee: "",
    queue: "General Support",
    statusReason: "",
    onHoldUntil: "",
    channel: "Chat",
    severity: "Minor",
    productArea: "Invoice Notifications",
    category: "Configuration / Reminder cadence",
    region: "North America",
    source: "Live chat",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-11 09:30 CET",
    resolutionTarget: "2026-04-14 17:00 CET",
    firstResponse: "",
    lastUpdate: "2026-04-11 08:19 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Harborview Clinics",
    contact: "Tessa Morgan",
    email: "tessa.morgan@harborview.example",
    accountTier: "Standard",
    contractType: "Standard monthly plan",
    routingGroup: "General Support",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer wants to know whether overdue invoice reminders can be delayed by two business days for a subset of self-pay clinics.",
    internalNotes:
      "Confirm whether reminder cadence can be configured per clinic segment or only at account level before assigning the case to the notifications owner.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "CHAT-SES-441102",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10519",
    title: "Customer still needs to confirm corrected statement branding across all clinics",
    status: "In progress",
    state: "Waiting on customer",
    blockingReason: "awaiting_customer_reply",
    priority: "Medium",
    assignee: "Lucia Fernandez",
    queue: "Document Delivery",
    statusReason: "Waiting for the customer to confirm the corrected branding on regenerated statements.",
    onHoldUntil: "2026-04-12",
    channel: "Email",
    severity: "Minor",
    productArea: "Statement Delivery",
    category: "Document templates / Regional branding",
    region: "Latin America",
    source: "Customer Support Mailbox",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-10 10:00 CET",
    resolutionTarget: "2026-04-12 17:00 CET",
    firstResponse: "2026-04-10 10:18 CET",
    lastUpdate: "2026-04-10 11:08 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Grupo Medico Esperanza",
    contact: "Valeria Soto",
    email: "valeria.soto@esperanza.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Document Delivery",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Regenerated customer statements include the updated regional branding, but the customer has not yet confirmed the final output across all clinics.",
    internalNotes:
      "Leave the case in the waiting state until the customer validates the corrected statement layout in their production tenant.",
    emailThreadId: "THR-884602",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10521",
    title: "Cross-border invoice bundle is calculating with the wrong tax rule",
    status: "In progress",
    state: "Escalated",
    blockingReason: "awaiting_approval",
    priority: "Critical",
    assignee: "Amelie Laurent",
    queue: "Platform Escalations",
    statusReason: "Escalated after finance leadership flagged a tax-rule mismatch affecting a same-day invoice release.",
    onHoldUntil: "",
    channel: "Phone",
    severity: "Critical",
    productArea: "Tax Rules Engine",
    category: "Tax configuration / Cross-border invoice bundle",
    region: "Central Europe",
    source: "Executive escalation hotline",
    timelinePolicy: "Enterprise Plus - Executive Escalation",
    responseTarget: "2026-04-11 09:00 CET",
    resolutionTarget: "2026-04-11 15:00 CET",
    firstResponse: "2026-04-11 08:52 CET",
    lastUpdate: "2026-04-11 09:18 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Helios Care Network",
    contact: "Lena Fischer",
    email: "lena.fischer@helioscare.example",
    accountTier: "Enterprise Plus",
    contractType: "Enterprise subscription with executive escalation coverage",
    routingGroup: "Platform Escalations",
    approvalRequired: "Yes",
    approvalReason: "Tax-engine rule override requires product and compliance approval before execution.",
    description:
      "A cross-border invoice bundle is calculating with the wrong tax rule for a subset of clinics, and leadership requested an immediate executive escalation.",
    internalNotes:
      "Track approvals tightly before applying any corrective override to the production tax-rule set.",
    emailThreadId: "",
    callReference: "CALL-2026-04-11-0907",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10509",
    title: "Customer needs access to archived remittance files from the prior fiscal quarter",
    status: "Resolved",
    state: "",
    blockingReason: "none",
    priority: "Low",
    assignee: "Chiara Marino",
    queue: "Customer Operations",
    statusReason: "Archived files were restored and the customer confirmed access to the prior quarter package.",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Minor",
    productArea: "Remittance Archive",
    category: "Data access / Archived financial records",
    region: "Southern Europe",
    source: "Customer Self-Service Portal",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-09 14:00 CET",
    resolutionTarget: "2026-04-10 17:00 CET",
    firstResponse: "2026-04-09 13:41 CET",
    lastUpdate: "2026-04-09 17:36 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Clinica Vista Serena",
    contact: "Miguel Ortega",
    email: "miguel.ortega@vistaserena.example",
    accountTier: "Standard",
    contractType: "Standard annual plan",
    routingGroup: "Customer Operations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer asked for access to archived remittance files from the prior fiscal quarter after their finance audit reopened a closed reconciliation task.",
    internalNotes:
      "Link the restored archive package reference in the record and close the case once the audit request is fully documented.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
]

export const activityTimelineItems: ActivityTimelineItem[] = [
  {
    id: "activity-0",
    timestamp: "Apr 1, 2026, 08:54 CET",
    timestampDateTime: "2026-04-01T08:54:00+02:00",
    type: "incoming",
    actor: "Marta Ruiz",
    subtype: "Customer",
    organization: "Viva la Vita Clinics SL",
    content:
      "Hi, we're still unable to access the invoice portal after resetting the password twice. This is blocking our finance team. Could you take a look?",
  },
  {
    id: "activity-1",
    timestamp: "Apr 1, 2026, 09:07 CET",
    timestampDateTime: "2026-04-01T09:07:00+02:00",
    type: "outgoing",
    actor: "Lucia Fernandez",
    subtype: "Support agent",
    organization: "VivaLaVita",
    content:
      "Thanks for flagging this, Marta. We've opened the case and are reviewing the invoice portal access state now. Please hold off on any additional password resets while we investigate.",
  },
  {
    id: "activity-2",
    timestamp: "Apr 1, 2026, 09:18 CET",
    timestampDateTime: "2026-04-01T09:18:00+02:00",
    type: "comment",
    actor: "Lucia Fernandez",
    subtype: "Support operations",
    organization: "VivaLaVita",
    content:
      "Customer confirmed the same access failure affects the finance lead in the clinic group. Preserve the current session logs while IAM validates the tenant-state mismatch.",
  },
  {
    id: "activity-3",
    timestamp: "Apr 1, 2026, 09:26 CET",
    timestampDateTime: "2026-04-01T09:26:00+02:00",
    type: "system",
    actor: "Identity monitor",
    subtype: "System",
    content:
      "Identity-service monitor detected a tenant-state mismatch between billing portal access roles and the clinic account profile.",
  },
  {
    id: "activity-4",
    timestamp: "Apr 1, 2026, 09:34 CET",
    timestampDateTime: "2026-04-01T09:34:00+02:00",
    type: "status-change",
    actor: "Auto-routing rule",
    subtype: "System",
    content:
      "Case moved from New to In progress and was assigned to Billing Portal Support after the portal access recovery workflow matched the incident pattern.",
  },
  {
    id: "activity-5",
    timestamp: "Apr 1, 2026, 09:41 CET",
    timestampDateTime: "2026-04-01T09:41:00+02:00",
    type: "outgoing",
    actor: "Lucia Fernandez",
    subtype: "Support agent",
    organization: "VivaLaVita",
    content:
      "We've corrected the account state and resynchronized the affected finance roles. When you have a moment, could you confirm that the impacted users can sign in again and see their invoices?",
  },
]

export const activityTimelineItemsByCaseId: Record<string, ActivityTimelineItem[]> = {
  "CASE-10482": activityTimelineItems,
  "CASE-10463": [
    {
      id: "case-10463-activity-0",
      timestamp: "Apr 1, 2026, 08:42 CET",
      timestampDateTime: "2026-04-01T08:42:00+02:00",
      type: "incoming",
      actor: "Eva Kruger",
      subtype: "Customer",
      organization: "Nordstern Dental Group",
      content:
        "We are seeing duplicate payment confirmation emails and some invoices look paid twice after this morning's payment batch.",
    },
    {
      id: "case-10463-activity-1",
      timestamp: "Apr 1, 2026, 08:49 CET",
      timestampDateTime: "2026-04-01T08:49:00+02:00",
      type: "system",
      actor: "Routing engine",
      subtype: "System",
      content:
        "Case ownership moved from General Support to Billing Operations after payment-batch signals matched the duplicate confirmation workflow.",
    },
    {
      id: "case-10463-activity-2",
      timestamp: "Apr 1, 2026, 08:55 CET",
      timestampDateTime: "2026-04-01T08:55:00+02:00",
      type: "outgoing",
      actor: "Jonas Weber",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks for reporting this. We're validating the duplicate confirmation pattern now and will confirm which invoices were actually affected before any corrections are made.",
    },
    {
      id: "case-10463-activity-3",
      timestamp: "Apr 1, 2026, 09:08 CET",
      timestampDateTime: "2026-04-01T09:08:00+02:00",
      type: "comment",
      actor: "Jonas Weber",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Confirmed that duplicate confirmation records are tied to a single reconciliation window. Billing operations is reviewing webhook deduplication before any invoice repair.",
    },
    {
      id: "case-10463-activity-4",
      timestamp: "Apr 1, 2026, 09:37 CET",
      timestampDateTime: "2026-04-01T09:37:00+02:00",
      type: "system",
      actor: "Payments monitor",
      subtype: "System",
      content:
        "Reconciliation monitor flagged a spike in duplicate confirmation events for the 08:00 CET payment batch.",
    },
    {
      id: "case-10463-activity-5",
      timestamp: "Apr 1, 2026, 11:22 CET",
      timestampDateTime: "2026-04-01T11:22:00+02:00",
      type: "outgoing",
      actor: "Jonas Weber",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We've isolated the duplicate confirmation pattern and are validating affected invoices before we make any customer-visible corrections.",
    },
  ],
  "CASE-10511": [
    {
      id: "case-10511-activity-0",
      timestamp: "Apr 1, 2026, 09:54 CET",
      timestampDateTime: "2026-04-01T09:54:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Invoices from our merged clinic entity are still missing in the portal until the nightly sync finishes. This started right after the tenant migration.",
    },
    {
      id: "case-10511-activity-1",
      timestamp: "Apr 1, 2026, 10:05 CET",
      timestampDateTime: "2026-04-01T10:05:00+02:00",
      type: "outgoing",
      actor: "Marco Silva",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks, Paolo. We've confirmed the tenant migration detail and are checking why the merged clinic invoices do not appear until the nightly sync completes.",
    },
    {
      id: "case-10511-activity-2",
      timestamp: "Apr 1, 2026, 10:14 CET",
      timestampDateTime: "2026-04-01T10:14:00+02:00",
      type: "status-change",
      actor: "Marco Silva",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from New to In progress after support confirmed the issue is reproducible and tied to a tenant-state sync delay.",
    },
    {
      id: "case-10511-activity-3",
      timestamp: "Apr 1, 2026, 11:03 CET",
      timestampDateTime: "2026-04-01T11:03:00+02:00",
      type: "system",
      actor: "Sync monitor",
      subtype: "System",
      content:
        "Tenant propagation job reported delayed sync completion for merged clinic entities after the latest migration window.",
    },
    {
      id: "case-10511-activity-4",
      timestamp: "Apr 1, 2026, 12:06 CET",
      timestampDateTime: "2026-04-01T12:06:00+02:00",
      type: "comment",
      actor: "Marco Silva",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Engineering is preparing a repair for the tenant-state sync job. Keep the case in active ownership until the internal fix is deployed.",
    },
  ],
  "CASE-10504": [
    {
      id: "case-10504-activity-0",
      timestamp: "Apr 1, 2026, 09:05 CET",
      timestampDateTime: "2026-04-01T09:05:00+02:00",
      type: "incoming",
      actor: "Sofia Bennett",
      subtype: "Customer",
      organization: "Northlake Medical Network",
      content:
        "Finance admins across our merged entities can only see a partial invoice list after the tenant migration. This needs executive visibility today.",
    },
    {
      id: "case-10504-activity-1",
      timestamp: "Apr 1, 2026, 09:18 CET",
      timestampDateTime: "2026-04-01T09:18:00+02:00",
      type: "status-change",
      typeLabel: "State change",
      actor: "Amelie Laurent",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case state moved to Escalated and ownership shifted to Platform Escalations after support confirmed the visibility issue affects multiple merged entities.",
    },
    {
      id: "case-10504-activity-2",
      timestamp: "Apr 1, 2026, 09:26 CET",
      timestampDateTime: "2026-04-01T09:26:00+02:00",
      type: "outgoing",
      actor: "Amelie Laurent",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We've escalated this to platform engineering and are treating it as a leadership-visible incident. We'll share the next confirmed findings in the next update window.",
    },
    {
      id: "case-10504-activity-3",
      timestamp: "Apr 1, 2026, 10:02 CET",
      timestampDateTime: "2026-04-01T10:02:00+02:00",
      type: "system",
      actor: "Routing engine",
      subtype: "System",
      content:
        "Escalation routing matched the case to the tenant migration visibility workflow and assigned executive escalation coverage.",
    },
    {
      id: "case-10504-activity-4",
      timestamp: "Apr 1, 2026, 11:08 CET",
      timestampDateTime: "2026-04-01T11:08:00+02:00",
      type: "comment",
      actor: "Amelie Laurent",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Keep the rollback window open until platform engineering confirms the full invoice visibility scope across all merged entities.",
    },
    {
      id: "case-10504-activity-5",
      timestamp: "Apr 1, 2026, 12:34 CET",
      timestampDateTime: "2026-04-01T12:34:00+02:00",
      type: "outgoing",
      actor: "Amelie Laurent",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Platform engineering is actively reviewing the visibility scopes. We'll share the next confirmed findings in the next update window.",
    },
  ],
  "CASE-10388": [
    {
      id: "case-10388-activity-0",
      timestamp: "Apr 1, 2026, 14:12 CET",
      timestampDateTime: "2026-04-01T14:12:00+02:00",
      type: "incoming",
      actor: "Ana Perez",
      subtype: "Customer",
      organization: "Vida Clara Centro Medico",
      content:
        "Can VAT labels in invoice exports be renamed for our local market?",
    },
    {
      id: "case-10388-activity-1",
      timestamp: "Apr 1, 2026, 14:14 CET",
      timestampDateTime: "2026-04-01T14:14:00+02:00",
      type: "system",
      actor: "Chat routing rule",
      subtype: "System",
      content:
        "Chat intake routed the request to General Support because the customer asked for a configuration clarification rather than reporting an incident.",
    },
    {
      id: "case-10388-activity-2",
      timestamp: "Apr 1, 2026, 14:16 CET",
      timestampDateTime: "2026-04-01T14:16:00+02:00",
      type: "comment",
      actor: "Anais Martin",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Assigned to General Support. Awaiting first response while we confirm whether VAT labels can be configured per export template.",
    },
  ],
  "CASE-10412": [
    {
      id: "case-10412-activity-0",
      timestamp: "Mar 31, 2026, 13:34 CET",
      timestampDateTime: "2026-03-31T13:34:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Our finance users still cannot access the billing portal this afternoon. Password reset did not restore access.",
    },
    {
      id: "case-10412-activity-1",
      timestamp: "Mar 31, 2026, 13:42 CET",
      timestampDateTime: "2026-03-31T13:42:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks for reporting this. We have opened an incident and are reviewing the portal access state now.",
    },
    {
      id: "case-10412-activity-2",
      timestamp: "Mar 31, 2026, 13:49 CET",
      timestampDateTime: "2026-03-31T13:49:00+02:00",
      type: "status-change",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from New to In progress after support confirmed the access failure affects multiple finance users.",
    },
    {
      id: "case-10412-activity-3",
      timestamp: "Mar 31, 2026, 14:06 CET",
      timestampDateTime: "2026-03-31T14:06:00+02:00",
      type: "system",
      actor: "Identity monitor",
      subtype: "System",
      content:
        "Identity-service monitor detected a tenant-state mismatch between billing portal access roles and the clinic account profile.",
    },
    {
      id: "case-10412-activity-4",
      timestamp: "Mar 31, 2026, 14:18 CET",
      timestampDateTime: "2026-03-31T14:18:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Captured current session logs and requested IAM validation before asking the customer to retry access.",
    },
    {
      id: "case-10412-activity-5",
      timestamp: "Mar 31, 2026, 15:02 CET",
      timestampDateTime: "2026-03-31T15:02:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We found an account-state issue and are applying a remediation. Please hold off on additional password resets while we complete the repair.",
    },
    {
      id: "case-10412-activity-6",
      timestamp: "Mar 31, 2026, 16:11 CET",
      timestampDateTime: "2026-03-31T16:11:00+02:00",
      type: "system",
      actor: "Access repair workflow",
      subtype: "System",
      content:
        "Tenant-state remediation completed and billing portal role assignments were resynchronized for the affected clinic account.",
    },
    {
      id: "case-10412-activity-7",
      timestamp: "Mar 31, 2026, 16:28 CET",
      timestampDateTime: "2026-03-31T16:28:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Internal validation passed for both finance users. Prepared customer follow-up asking for live confirmation from the clinic team.",
    },
    {
      id: "case-10412-activity-8",
      timestamp: "Apr 1, 2026, 08:37 CET",
      timestampDateTime: "2026-04-01T08:37:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Confirmed that both finance users can sign in again and invoices are visible. Please send us a written resolution summary for our records.",
    },
    {
      id: "case-10412-activity-9",
      timestamp: "Apr 1, 2026, 08:52 CET",
      timestampDateTime: "2026-04-01T08:52:00+02:00",
      type: "status-change",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from In progress to Resolved after the customer confirmed access was restored and invoice visibility returned.",
    },
    {
      id: "case-10412-activity-10",
      timestamp: "Apr 1, 2026, 09:04 CET",
      timestampDateTime: "2026-04-01T09:04:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Shared a written resolution summary describing the account-state mismatch, the remediation performed, and the verification steps completed.",
    },
    {
      id: "case-10412-activity-11",
      timestamp: "Apr 1, 2026, 16:18 CET",
      timestampDateTime: "2026-04-01T16:18:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Filed the post-incident note, linked the IAM repair reference, and queued the case for standard closure confirmation tracking.",
    },
    {
      id: "case-10412-activity-12",
      timestamp: "Apr 2, 2026, 10:14 CET",
      timestampDateTime: "2026-04-02T10:14:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Thanks for the summary. We have everything we need and can close the incident on our side.",
    },
  ],
  "CASE-10519": [
    {
      id: "case-10519-activity-0",
      timestamp: "Apr 10, 2026, 09:44 CET",
      timestampDateTime: "2026-04-10T09:44:00+02:00",
      type: "incoming",
      actor: "Valeria Soto",
      subtype: "Customer",
      organization: "Grupo Medico Esperanza",
      content:
        "The regenerated statements look closer, but we still need to confirm whether the updated branding is correct across all clinics before we sign this off.",
    },
    {
      id: "case-10519-activity-1",
      timestamp: "Apr 10, 2026, 10:18 CET",
      timestampDateTime: "2026-04-10T10:18:00+02:00",
      type: "outgoing",
      actor: "Lucia Fernandez",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks, Valeria. When you have a moment, could you confirm whether the corrected branding is now approved for all clinic statements, or let us know which entity still needs adjustment?",
    },
    {
      id: "case-10519-activity-2",
      timestamp: "Apr 10, 2026, 11:08 CET",
      timestampDateTime: "2026-04-10T11:08:00+02:00",
      type: "comment",
      actor: "Lucia Fernandez",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Customer confirmation is still pending after the clarification request. Keep the case in the waiting state until they validate the final statement set.",
    },
  ],
  "CASE-10516": [
    {
      id: "case-10516-activity-0",
      timestamp: "Apr 10, 2026, 10:48 CET",
      timestampDateTime: "2026-04-10T10:48:00+02:00",
      type: "incoming",
      actor: "Irene Costa",
      subtype: "Customer",
      organization: "Clinica Mar Azul",
      content:
        "Today's settlement export is missing the low-volume adjustment rows for several clinics, so our finance team is reconciling them manually.",
    },
    {
      id: "case-10516-activity-1",
      timestamp: "Apr 10, 2026, 11:04 CET",
      timestampDateTime: "2026-04-10T11:04:00+02:00",
      type: "outgoing",
      actor: "Nadia Romero",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks for flagging this. We're validating the settlement export now and will confirm whether the missing adjustment rows are limited to the affected clinics.",
    },
    {
      id: "case-10516-activity-2",
      timestamp: "Apr 10, 2026, 11:26 CET",
      timestampDateTime: "2026-04-10T11:26:00+02:00",
      type: "system",
      actor: "Export monitor",
      subtype: "System",
      content:
        "Settlement export monitoring detected adjustment rows posted after the batch cutoff were omitted from the summary file for a subset of clinic entities.",
    },
    {
      id: "case-10516-activity-3",
      timestamp: "Apr 10, 2026, 12:03 CET",
      timestampDateTime: "2026-04-10T12:03:00+02:00",
      type: "status-change",
      actor: "Routing engine",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case ownership moved from Billing Operations to Finance Integrations after support confirmed the issue sits in settlement export logic rather than reconciliation workflow.",
    },
    {
      id: "case-10516-activity-4",
      timestamp: "Apr 11, 2026, 08:27 CET",
      timestampDateTime: "2026-04-11T08:27:00+02:00",
      type: "comment",
      actor: "Nadia Romero",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Initial analysis suggests the export job skips low-volume adjustments that post after the batch window but before summary generation. Investigation remains active while we validate the affected clinics.",
    },
  ],
  "CASE-10518": [
    {
      id: "case-10518-activity-0",
      timestamp: "Apr 11, 2026, 08:12 CET",
      timestampDateTime: "2026-04-11T08:12:00+02:00",
      type: "incoming",
      actor: "Tessa Morgan",
      subtype: "Customer",
      organization: "Harborview Clinics",
      content:
        "Can overdue invoice reminders be delayed by two business days for a subset of our self-pay clinics?",
    },
    {
      id: "case-10518-activity-1",
      timestamp: "Apr 11, 2026, 08:15 CET",
      timestampDateTime: "2026-04-11T08:15:00+02:00",
      type: "system",
      actor: "Chat routing rule",
      subtype: "System",
      content:
        "Chat intake routed the configuration request to General Support because no automation failure or delivery incident was detected.",
    },
    {
      id: "case-10518-activity-2",
      timestamp: "Apr 11, 2026, 08:19 CET",
      timestampDateTime: "2026-04-11T08:19:00+02:00",
      type: "comment",
      actor: "Triage queue",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Queued for assignment. Need to confirm whether reminder cadence can be configured per clinic segment before sending the first response.",
    },
  ],
  "CASE-10521": [
    {
      id: "case-10521-activity-0",
      timestamp: "Apr 11, 2026, 08:31 CET",
      timestampDateTime: "2026-04-11T08:31:00+02:00",
      type: "incoming",
      actor: "Lena Fischer",
      subtype: "Customer",
      organization: "Helios Care Network",
      content:
        "A subset of clinics in today's cross-border invoice bundle is calculating with the wrong tax rule. We need this corrected before the noon release.",
    },
    {
      id: "case-10521-activity-1",
      timestamp: "Apr 11, 2026, 08:52 CET",
      timestampDateTime: "2026-04-11T08:52:00+02:00",
      type: "outgoing",
      actor: "Amelie Laurent",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We've opened an executive escalation and are validating the affected clinics now. We'll confirm the approval path before any tax-rule override is applied.",
    },
    {
      id: "case-10521-activity-2",
      timestamp: "Apr 11, 2026, 09:03 CET",
      timestampDateTime: "2026-04-11T09:03:00+02:00",
      type: "status-change",
      typeLabel: "State change",
      actor: "Amelie Laurent",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case state moved to Escalated and ownership shifted to Platform Escalations because product and compliance approval is required before a production tax override.",
    },
    {
      id: "case-10521-activity-3",
      timestamp: "Apr 11, 2026, 09:11 CET",
      timestampDateTime: "2026-04-11T09:11:00+02:00",
      type: "system",
      actor: "Approval workflow",
      subtype: "System",
      content:
        "Approval workflow opened a product-and-compliance signoff request for the cross-border tax-rule override before the same-day invoice release.",
    },
    {
      id: "case-10521-activity-4",
      timestamp: "Apr 11, 2026, 09:18 CET",
      timestampDateTime: "2026-04-11T09:18:00+02:00",
      type: "comment",
      actor: "Amelie Laurent",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Track approvals tightly before applying any corrective override to the production tax-rule set. Finance leadership needs the next checkpoint as soon as signoff is complete.",
    },
  ],
  "CASE-10509": [
    {
      id: "case-10509-activity-0",
      timestamp: "Apr 9, 2026, 13:28 CET",
      timestampDateTime: "2026-04-09T13:28:00+02:00",
      type: "incoming",
      actor: "Miguel Ortega",
      subtype: "Customer",
      organization: "Clinica Vista Serena",
      content:
        "We need access to the archived remittance files from the prior fiscal quarter because our finance audit reopened the reconciliation review.",
    },
    {
      id: "case-10509-activity-1",
      timestamp: "Apr 9, 2026, 13:41 CET",
      timestampDateTime: "2026-04-09T13:41:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks, Miguel. We're restoring the archived package now and will confirm access once the prior-quarter remittance files are available.",
    },
    {
      id: "case-10509-activity-2",
      timestamp: "Apr 9, 2026, 14:22 CET",
      timestampDateTime: "2026-04-09T14:22:00+02:00",
      type: "system",
      actor: "Archive retrieval workflow",
      subtype: "System",
      content:
        "Archive retrieval started for the prior fiscal quarter remittance package and restored the secure download workspace for the requesting account.",
    },
    {
      id: "case-10509-activity-3",
      timestamp: "Apr 9, 2026, 15:08 CET",
      timestampDateTime: "2026-04-09T15:08:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Validated that the restored package contains the full prior-quarter remittance file set requested by the finance audit team.",
    },
    {
      id: "case-10509-activity-4",
      timestamp: "Apr 9, 2026, 16:12 CET",
      timestampDateTime: "2026-04-09T16:12:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We've restored access to the archived remittance package and shared the secure download instructions. Please confirm the files cover everything your audit team needs.",
    },
    {
      id: "case-10509-activity-5",
      timestamp: "Apr 9, 2026, 17:36 CET",
      timestampDateTime: "2026-04-09T17:36:00+02:00",
      type: "incoming",
      actor: "Miguel Ortega",
      subtype: "Customer",
      organization: "Clinica Vista Serena",
      content:
        "Confirmed that we can access the full prior-quarter package now. This covers everything the audit team needed.",
    },
  ],
}
