import type { ActivityTimelineItem } from "../design-system/components/ActivityTimeline"
import type { CaseRecord } from "../design-system/case-record/types"

export const INITIAL_CASE_RECORD: CaseRecord = {
  title: "Customer cannot access invoice portal",
  id: "CASE-10482",
  status: "Waiting on customer",
  blockingReason: "awaiting_customer_validation",
  priority: "High",
  assignee: "Lucia Fernandez",
  queue: "Billing Portal Support",
  statusReason: "Awaiting customer confirmation after account remediation.",
  onHoldUntil: "2026-04-02",
  channel: "Email",
  severity: "Major",
  productArea: "Billing Portal",
  category: "Access & Authentication / Multi-factor Access Recovery",
  region: "Southern Europe",
  source: "Customer Support Mailbox",
  timelinePolicy: "Enterprise Plus - Standard Incident",
  responseTarget: "2026-04-01 10:15 CET",
  resolutionTarget: "2026-04-02 17:00 CET",
  firstResponse: "2026-04-01 09:07 CET",
  lastUpdate: "2026-04-01 09:41 CET",
  slaStatus: "At risk",
  breachRisk: "Medium",
  customer: "Viva la Vita Clinics SL",
  contact: "Marta Ruiz",
  email: "marta@vivalavita.com",
  accountTier: "Enterprise Plus",
  contractType: "Enterprise subscription with 24/7 support addendum",
  routingGroup: "Portal Access Recovery",
  approvalRequired: "No",
  approvalReason: "Leadership approval needed for accelerated customer credit.",
  description:
    "Customer reset password twice and still cannot access the billing portal. Recent routing notes suggest a tenant-state mismatch between identity services and the billing portal.",
  internalNotes:
    "Coordinate with IAM before asking the customer to retry. Preserve the current session logs and confirm whether the issue affects all finance users in the clinic group.",
  emailThreadId: "THR-884291",
  callReference: "CALL-2026-04-01-1184",
  chatSessionId: "CHAT-SES-440218",
}

export const EXAMPLE_CASES: CaseRecord[] = [
  INITIAL_CASE_RECORD,
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10463",
    title: "European clinic cannot reconcile duplicate payment confirmations in billing portal",
    status: "In progress",
    blockingReason: "none",
    priority: "Critical",
    assignee: "Jonas Weber",
    queue: "Billing Operations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Critical",
    productArea: "Payments Reconciliation",
    category: "Transactions / Duplicate confirmation records",
    region: "Central Europe",
    source: "Customer Self-Service Portal",
    responseTarget: "2026-04-01 09:15 CET",
    resolutionTarget: "2026-04-01 13:00 CET",
    firstResponse: "2026-04-01 08:58 CET",
    lastUpdate: "2026-04-01 11:22 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Nordstern Dental Group",
    contact: "Eva Kruger",
    email: "eva.kruger@nordstern.example",
    accountTier: "Enterprise",
    contractType: "Enterprise subscription",
    routingGroup: "Payments Escalations",
    description:
      "Customer reports duplicate payment confirmation emails and mismatched invoice statuses after a batch of portal-submitted payments.",
    internalNotes:
      "Cross-check payment gateway webhooks against billing reconciliation logs before reprocessing any invoices.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10511",
    title: "Nightly tenant sync is delaying invoice visibility after clinic merge",
    status: "In progress",
    blockingReason: "awaiting_engineering_fix",
    priority: "High",
    assignee: "Marco Silva",
    queue: "Billing Integrations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Major",
    productArea: "Tenant Data Sync",
    category: "Visibility & Permissions / Post-migration propagation",
    region: "Central Europe",
    source: "Customer Self-Service Portal",
    timelinePolicy: "Enterprise Plus - Standard Incident",
    responseTarget: "2026-04-01 11:00 CET",
    resolutionTarget: "2026-04-02 15:00 CET",
    firstResponse: "2026-04-01 10:14 CET",
    lastUpdate: "2026-04-01 12:06 CET",
    slaStatus: "At risk",
    breachRisk: "Medium",
    customer: "Clinica Sorella",
    contact: "Paolo Vitale",
    email: "paolo.vitale@clinicasorella.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Billing Integrations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Merged clinic invoices are not visible until the nightly tenant sync completes, leaving finance teams with partial invoice views throughout the day.",
    internalNotes:
      "Platform engineering is preparing a sync repair for the tenant-state propagation job. Keep the customer updated while the internal fix is in progress.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10504",
    title: "Escalated review for multi-market invoice visibility issue affecting finance administrators across merged clinic entities after tenant migration",
    status: "Escalated",
    blockingReason: "none",
    priority: "High",
    assignee: "Amelie Laurent",
    queue: "Platform Escalations",
    statusReason: "Escalated to platform engineering after tenant migration logs showed inconsistent visibility scopes.",
    onHoldUntil: "",
    channel: "Phone",
    severity: "Major",
    productArea: "Tenant Administration",
    category: "Visibility & Permissions / Cross-entity access",
    region: "North America",
    source: "Executive escalation hotline",
    timelinePolicy: "Enterprise Plus - Executive Escalation",
    responseTarget: "2026-04-01 10:00 CET",
    resolutionTarget: "2026-04-02 12:00 CET",
    firstResponse: "2026-04-01 09:18 CET",
    lastUpdate: "2026-04-01 12:34 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Northlake Medical Network",
    contact: "Sofia Bennett",
    email: "sofia.bennett@northlake.example",
    accountTier: "Enterprise Plus",
    contractType: "Enterprise subscription with executive escalation coverage",
    routingGroup: "Platform Escalations",
    approvalRequired: "Yes",
    approvalReason: "Engineering manager approval required before running tenant visibility repair.",
    description:
      "Finance admins from merged entities can see only a partial subset of invoices after a tenant migration and permissions sync.",
    internalNotes:
      "Keep the rollback window open until visibility results are confirmed across all merged entities.",
    emailThreadId: "",
    callReference: "CALL-2026-04-01-1219",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10388",
    title: "New onboarding question about VAT labels in the invoice export",
    status: "New",
    blockingReason: "",
    priority: "",
    assignee: "",
    queue: "General Support",
    statusReason: "",
    onHoldUntil: "",
    channel: "Chat",
    severity: "Minor",
    productArea: "Invoice Export",
    category: "Configuration / Tax labels",
    region: "Latin America",
    source: "Live chat",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-01 15:00 CET",
    resolutionTarget: "2026-04-03 17:00 CET",
    firstResponse: "",
    lastUpdate: "2026-04-01 14:12 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Vida Clara Centro Medico",
    contact: "Ana Perez",
    email: "ana.perez@vidaclara.example",
    accountTier: "Standard",
    contractType: "Standard monthly plan",
    routingGroup: "General Support",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer wants to understand whether VAT labels in exported invoices can be renamed for a local market workflow.",
    internalNotes:
      "Useful sparse record to test missing owner and priority in both list and detail views.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "CHAT-SES-440901",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10412",
    title: "Regional operations lead requests closure confirmation for resolved access incident",
    status: "Resolved",
    blockingReason: "none",
    priority: "Medium",
    assignee: "Chiara Marino",
    queue: "Customer Operations",
    statusReason: "Access restored and customer notified. Waiting for formal closure acknowledgement.",
    onHoldUntil: "",
    channel: "Email",
    severity: "Minor",
    productArea: "Billing Portal",
    category: "Access & Authentication / Resolution confirmation",
    region: "Southern Europe",
    source: "Customer Support Mailbox",
    timelinePolicy: "Enterprise Standard",
    responseTarget: "2026-03-31 14:00 CET",
    resolutionTarget: "2026-04-01 17:00 CET",
    firstResponse: "2026-03-31 13:42 CET",
    lastUpdate: "2026-04-02 10:14 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Clinica Sorella",
    contact: "Paolo Vitale",
    email: "paolo.vitale@clinicasorella.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Customer Operations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer requested written confirmation that portal access was fully restored after the previous incident.",
    internalNotes:
      "Resolved example kept intentionally complete so the record page can be tested with a long, realistic lifecycle timeline.",
    emailThreadId: "THR-884140",
    callReference: "",
    chatSessionId: "",
  },
]

export const activityTimelineItems: ActivityTimelineItem[] = [
  {
    id: "activity-0",
    timestamp: "Apr 1, 2026, 08:54 CET",
    timestampDateTime: "2026-04-01T08:54:00+02:00",
    type: "incoming",
    actor: "Marta Ruiz",
    subtype: "Customer",
    organization: "Green Valley Clinic",
    content:
      "Hi, we're still unable to access the invoice portal after resetting the password twice. This is blocking our finance team. Could you take a look?",
  },
  {
    id: "activity-1",
    timestamp: "Apr 1, 2026, 09:07 CET",
    timestampDateTime: "2026-04-01T09:07:00+02:00",
    type: "comment",
    actor: "Lucia Fernandez",
    subtype: "Support operations",
    organization: "VivaLaVita",
    content:
      "Customer confirmed that invoice portal access still fails after two password resets and that the same issue affects the finance lead in the clinic group.",
  },
  {
    id: "activity-1b",
    timestamp: "Apr 1, 2026, 09:18 CET",
    timestampDateTime: "2026-04-01T09:18:00+02:00",
    type: "outgoing",
    actor: "Lucia Fernandez",
    subtype: "Support agent",
    organization: "VivaLaVita",
    content:
      "Hi Marta, thanks for reporting this. We’re currently investigating the issue with the invoice portal access. I’ll update you shortly once we confirm the root cause.",
  },
  {
    id: "activity-2",
    timestamp: "Apr 1, 2026, 09:26 CET",
    timestampDateTime: "2026-04-01T09:26:00+02:00",
    type: "status-change",
    actor: "Lucia Fernandez",
    subtype: "Support operations",
    organization: "VivaLaVita",
    content:
      "Case moved from New to In progress after support operations confirmed the incident is reproducible and requires account-state review.",
  },
  {
    id: "activity-3",
    timestamp: "Apr 1, 2026, 09:41 CET",
    timestampDateTime: "2026-04-01T09:41:00+02:00",
    type: "system",
    actor: "Auto-routing rule",
    subtype: "System",
    content:
      "Routing engine reassigned the case to Billing Portal Support because recent tenant-state signals matched the portal access recovery workflow.",
  },
  {
    id: "activity-4",
    timestamp: "Apr 1, 2026, 10:12 CET",
    timestampDateTime: "2026-04-01T10:12:00+02:00",
    type: "comment",
    actor: "Lucia Fernandez",
    subtype: "Internal note",
    organization: "VivaLaVita",
    content:
      "Internal note added to preserve current session logs and wait for identity-service confirmation before asking the customer to attempt another login.",
  },
]

export const activityTimelineItemsByCaseId: Record<string, ActivityTimelineItem[]> = {
  "CASE-10482": activityTimelineItems,
  "CASE-10463": [
    {
      id: "case-10463-activity-0",
      timestamp: "Apr 1, 2026, 08:42 CET",
      timestampDateTime: "2026-04-01T08:42:00+02:00",
      type: "incoming",
      actor: "Eva Kruger",
      subtype: "Customer",
      organization: "Nordstern Dental Group",
      content:
        "We are seeing duplicate payment confirmation emails and some invoices look paid twice after this morning's payment batch.",
    },
    {
      id: "case-10463-activity-1",
      timestamp: "Apr 1, 2026, 08:58 CET",
      timestampDateTime: "2026-04-01T08:58:00+02:00",
      type: "comment",
      actor: "Jonas Weber",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Confirmed that duplicate confirmation records are tied to a single reconciliation window. Billing operations is reviewing webhook deduplication before any invoice repair.",
    },
    {
      id: "case-10463-activity-2",
      timestamp: "Apr 1, 2026, 09:37 CET",
      timestampDateTime: "2026-04-01T09:37:00+02:00",
      type: "system",
      actor: "Payments monitor",
      subtype: "System",
      content:
        "Reconciliation monitor flagged a spike in duplicate confirmation events for the 08:00 CET payment batch.",
    },
    {
      id: "case-10463-activity-3",
      timestamp: "Apr 1, 2026, 11:22 CET",
      timestampDateTime: "2026-04-01T11:22:00+02:00",
      type: "outgoing",
      actor: "Jonas Weber",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We've isolated the duplicate confirmation pattern and are validating affected invoices before we make any customer-visible corrections.",
    },
  ],
  "CASE-10511": [
    {
      id: "case-10511-activity-0",
      timestamp: "Apr 1, 2026, 09:54 CET",
      timestampDateTime: "2026-04-01T09:54:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Invoices from our merged clinic entity are still missing in the portal until the nightly sync finishes. This started right after the tenant migration.",
    },
    {
      id: "case-10511-activity-1",
      timestamp: "Apr 1, 2026, 10:14 CET",
      timestampDateTime: "2026-04-01T10:14:00+02:00",
      type: "status-change",
      actor: "Marco Silva",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from New to In progress after support confirmed the issue is reproducible and tied to a tenant-state sync delay.",
    },
    {
      id: "case-10511-activity-2",
      timestamp: "Apr 1, 2026, 11:03 CET",
      timestampDateTime: "2026-04-01T11:03:00+02:00",
      type: "system",
      actor: "Sync monitor",
      subtype: "System",
      content:
        "Tenant propagation job reported delayed sync completion for merged clinic entities after the latest migration window.",
    },
    {
      id: "case-10511-activity-3",
      timestamp: "Apr 1, 2026, 12:06 CET",
      timestampDateTime: "2026-04-01T12:06:00+02:00",
      type: "comment",
      actor: "Marco Silva",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Engineering is preparing a repair for the tenant-state sync job. Keep the case in active ownership until the internal fix is deployed.",
    },
  ],
  "CASE-10504": [
    {
      id: "case-10504-activity-0",
      timestamp: "Apr 1, 2026, 09:05 CET",
      timestampDateTime: "2026-04-01T09:05:00+02:00",
      type: "incoming",
      actor: "Sofia Bennett",
      subtype: "Customer",
      organization: "Northlake Medical Network",
      content:
        "Finance admins across our merged entities can only see a partial invoice list after the tenant migration. This needs executive visibility today.",
    },
    {
      id: "case-10504-activity-1",
      timestamp: "Apr 1, 2026, 09:18 CET",
      timestampDateTime: "2026-04-01T09:18:00+02:00",
      type: "status-change",
      actor: "Amelie Laurent",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from In progress to Escalated and assigned to platform engineering for executive oversight while active investigation continues.",
    },
    {
      id: "case-10504-activity-2",
      timestamp: "Apr 1, 2026, 10:02 CET",
      timestampDateTime: "2026-04-01T10:02:00+02:00",
      type: "system",
      actor: "Routing engine",
      subtype: "System",
      content:
        "Escalation routing matched the case to the tenant migration visibility workflow and assigned executive escalation coverage.",
    },
    {
      id: "case-10504-activity-3",
      timestamp: "Apr 1, 2026, 12:34 CET",
      timestampDateTime: "2026-04-01T12:34:00+02:00",
      type: "outgoing",
      actor: "Amelie Laurent",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Platform engineering is actively reviewing the visibility scopes. We'll share the next confirmed findings in the next update window.",
    },
  ],
  "CASE-10388": [
    {
      id: "case-10388-activity-0",
      timestamp: "Apr 1, 2026, 14:12 CET",
      timestampDateTime: "2026-04-01T14:12:00+02:00",
      type: "incoming",
      actor: "Ana Perez",
      subtype: "Customer",
      organization: "Vida Clara Centro Medico",
      content:
        "Can VAT labels in invoice exports be renamed for our local market?",
    },
    {
      id: "case-10388-activity-1",
      timestamp: "Apr 1, 2026, 14:16 CET",
      timestampDateTime: "2026-04-01T14:16:00+02:00",
      type: "comment",
      actor: "Triage queue",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "New chat received. Needs ownership and product confirmation.",
    },
  ],
  "CASE-10412": [
    {
      id: "case-10412-activity-0",
      timestamp: "Mar 31, 2026, 13:34 CET",
      timestampDateTime: "2026-03-31T13:34:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Our finance users still cannot access the billing portal this afternoon. Password reset did not restore access.",
    },
    {
      id: "case-10412-activity-1",
      timestamp: "Mar 31, 2026, 13:42 CET",
      timestampDateTime: "2026-03-31T13:42:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Thanks for reporting this. We have opened an incident and are reviewing the portal access state now.",
    },
    {
      id: "case-10412-activity-2",
      timestamp: "Mar 31, 2026, 13:49 CET",
      timestampDateTime: "2026-03-31T13:49:00+02:00",
      type: "status-change",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from New to In progress after support confirmed the access failure affects multiple finance users.",
    },
    {
      id: "case-10412-activity-3",
      timestamp: "Mar 31, 2026, 14:06 CET",
      timestampDateTime: "2026-03-31T14:06:00+02:00",
      type: "system",
      actor: "Identity monitor",
      subtype: "System",
      content:
        "Identity-service monitor detected a tenant-state mismatch between billing portal access roles and the clinic account profile.",
    },
    {
      id: "case-10412-activity-4",
      timestamp: "Mar 31, 2026, 14:18 CET",
      timestampDateTime: "2026-03-31T14:18:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Captured current session logs and requested IAM validation before asking the customer to retry access.",
    },
    {
      id: "case-10412-activity-5",
      timestamp: "Mar 31, 2026, 15:02 CET",
      timestampDateTime: "2026-03-31T15:02:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "We found an account-state issue and are applying a remediation. Please hold off on additional password resets while we complete the repair.",
    },
    {
      id: "case-10412-activity-6",
      timestamp: "Mar 31, 2026, 16:11 CET",
      timestampDateTime: "2026-03-31T16:11:00+02:00",
      type: "system",
      actor: "Access repair workflow",
      subtype: "System",
      content:
        "Tenant-state remediation completed and billing portal role assignments were resynchronized for the affected clinic account.",
    },
    {
      id: "case-10412-activity-7",
      timestamp: "Mar 31, 2026, 16:28 CET",
      timestampDateTime: "2026-03-31T16:28:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Internal validation passed for both finance users. Prepared customer follow-up asking for live confirmation from the clinic team.",
    },
    {
      id: "case-10412-activity-8",
      timestamp: "Apr 1, 2026, 08:37 CET",
      timestampDateTime: "2026-04-01T08:37:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Confirmed that both finance users can sign in again and invoices are visible. Please send us a written resolution summary for our records.",
    },
    {
      id: "case-10412-activity-9",
      timestamp: "Apr 1, 2026, 08:52 CET",
      timestampDateTime: "2026-04-01T08:52:00+02:00",
      type: "status-change",
      actor: "Chiara Marino",
      subtype: "Support operations",
      organization: "VivaLaVita",
      content:
        "Case moved from In progress to Resolved after the customer confirmed access was restored and invoice visibility returned.",
    },
    {
      id: "case-10412-activity-10",
      timestamp: "Apr 1, 2026, 09:04 CET",
      timestampDateTime: "2026-04-01T09:04:00+02:00",
      type: "outgoing",
      actor: "Chiara Marino",
      subtype: "Support agent",
      organization: "VivaLaVita",
      content:
        "Shared a written resolution summary describing the account-state mismatch, the remediation performed, and the verification steps completed.",
    },
    {
      id: "case-10412-activity-11",
      timestamp: "Apr 1, 2026, 16:18 CET",
      timestampDateTime: "2026-04-01T16:18:00+02:00",
      type: "comment",
      actor: "Chiara Marino",
      subtype: "Internal note",
      organization: "VivaLaVita",
      content:
        "Filed the post-incident note, linked the IAM repair reference, and queued the case for standard closure confirmation tracking.",
    },
    {
      id: "case-10412-activity-12",
      timestamp: "Apr 2, 2026, 10:14 CET",
      timestampDateTime: "2026-04-02T10:14:00+02:00",
      type: "incoming",
      actor: "Paolo Vitale",
      subtype: "Customer",
      organization: "Clinica Sorella",
      content:
        "Thanks for the summary. We have everything we need and can close the incident on our side.",
    },
  ],
}
