import type { ActivityTimelineItem } from "../design-system/components/ActivityTimeline"
import type { CaseRecord } from "../design-system/case-record/types"

export const INITIAL_CASE_RECORD: CaseRecord = {
  title: "Customer cannot access invoice portal",
  id: "CASE-10482",
  status: "Waiting on customer",
  priority: "High",
  assignee: "Lucia Fernandez",
  queue: "Billing Portal Support",
  statusReason: "Awaiting customer confirmation after account remediation.",
  onHoldUntil: "2026-04-02",
  channel: "Email",
  severity: "Major",
  productArea: "Billing Portal",
  category: "Access & Authentication / Multi-factor Access Recovery",
  region: "Southern Europe",
  source: "Customer Support Mailbox",
  timelinePolicy: "Enterprise Plus - Standard Incident",
  responseTarget: "2026-04-01 10:15 CET",
  resolutionTarget: "2026-04-02 17:00 CET",
  firstResponse: "2026-04-01 09:07 CET",
  lastUpdate: "2026-04-01 09:41 CET",
  slaStatus: "At risk",
  breachRisk: "Medium",
  customer: "Viva la Vita Clinics SL",
  contact: "Marta Ruiz",
  email: "marta@vivalavita.com",
  accountTier: "Enterprise Plus",
  contractType: "Enterprise subscription with 24/7 support addendum",
  routingGroup: "Portal Access Recovery",
  approvalRequired: "No",
  approvalReason: "Leadership approval needed for accelerated customer credit.",
  description:
    "Customer reset password twice and still cannot access the billing portal. Recent routing notes suggest a tenant-state mismatch between identity services and the billing portal.",
  internalNotes:
    "Coordinate with IAM before asking the customer to retry. Preserve the current session logs and confirm whether the issue affects all finance users in the clinic group.",
  emailThreadId: "THR-884291",
  callReference: "CALL-2026-04-01-1184",
  chatSessionId: "CHAT-SES-440218",
}

export const EXAMPLE_CASES: CaseRecord[] = [
  INITIAL_CASE_RECORD,
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10463",
    title: "European clinic cannot reconcile duplicate payment confirmations in billing portal",
    status: "In progress",
    priority: "Critical",
    assignee: "Jonas Weber",
    queue: "Billing Operations",
    statusReason: "",
    onHoldUntil: "",
    channel: "Portal",
    severity: "Critical",
    productArea: "Payments Reconciliation",
    category: "Transactions / Duplicate confirmation records",
    region: "Central Europe",
    source: "Customer Self-Service Portal",
    responseTarget: "2026-04-01 09:15 CET",
    resolutionTarget: "2026-04-01 13:00 CET",
    firstResponse: "2026-04-01 08:58 CET",
    lastUpdate: "2026-04-01 11:22 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Nordstern Dental Group",
    contact: "Eva Kruger",
    email: "eva.kruger@nordstern.example",
    accountTier: "Enterprise",
    contractType: "Enterprise subscription",
    routingGroup: "Payments Escalations",
    description:
      "Customer reports duplicate payment confirmation emails and mismatched invoice statuses after a batch of portal-submitted payments.",
    internalNotes:
      "Cross-check payment gateway webhooks against billing reconciliation logs before reprocessing any invoices.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10412",
    title: "Regional operations lead requests closure confirmation for resolved access incident",
    status: "Resolved",
    priority: "Medium",
    assignee: "Chiara Marino",
    queue: "Customer Operations",
    statusReason: "Access restored and customer notified. Waiting for formal closure acknowledgement.",
    onHoldUntil: "",
    channel: "Email",
    severity: "Minor",
    productArea: "",
    category: "",
    region: "Southern Europe",
    source: "",
    timelinePolicy: "Enterprise Standard",
    responseTarget: "2026-03-31 14:00 CET",
    resolutionTarget: "2026-04-01 17:00 CET",
    firstResponse: "2026-03-31 13:42 CET",
    lastUpdate: "2026-04-01 16:18 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Clinica Sorella",
    contact: "Paolo Vitale",
    email: "paolo.vitale@clinicasorella.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Customer Operations",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer requested written confirmation that portal access was fully restored after the previous incident.",
    internalNotes:
      "Sparse routing metadata is intentional here to test read-only fallback handling in the record sections.",
    emailThreadId: "THR-884140",
    callReference: "",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10504",
    title: "Escalated review for multi-market invoice visibility issue affecting finance administrators across merged clinic entities after tenant migration",
    status: "Escalated",
    priority: "High",
    assignee: "Amelie Laurent",
    queue: "Platform Escalations",
    statusReason: "Escalated to platform engineering after tenant migration logs showed inconsistent visibility scopes.",
    onHoldUntil: "",
    channel: "Phone",
    severity: "Major",
    productArea: "Tenant Administration",
    category: "Visibility & Permissions / Cross-entity access",
    region: "North America",
    source: "Executive escalation hotline",
    timelinePolicy: "Enterprise Plus - Executive Escalation",
    responseTarget: "2026-04-01 10:00 CET",
    resolutionTarget: "2026-04-02 12:00 CET",
    firstResponse: "2026-04-01 09:18 CET",
    lastUpdate: "2026-04-01 12:34 CET",
    slaStatus: "At risk",
    breachRisk: "High",
    customer: "Northlake Medical Network",
    contact: "Sofia Bennett",
    email: "sofia.bennett@northlake.example",
    accountTier: "Enterprise Plus",
    contractType: "Enterprise subscription with executive escalation coverage",
    routingGroup: "Platform Escalations",
    approvalRequired: "Yes",
    approvalReason: "Engineering manager approval required before running tenant visibility repair.",
    description:
      "Finance admins from merged entities can see only a partial subset of invoices after a tenant migration and permissions sync.",
    internalNotes:
      "Keep the rollback window open until visibility results are confirmed across all merged entities.",
    emailThreadId: "",
    callReference: "CALL-2026-04-01-1219",
    chatSessionId: "",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10388",
    title: "New onboarding question about VAT labels in the invoice export",
    status: "New",
    priority: "",
    assignee: "",
    queue: "General Support",
    statusReason: "",
    onHoldUntil: "",
    channel: "Chat",
    severity: "Minor",
    productArea: "Invoice Export",
    category: "Configuration / Tax labels",
    region: "Latin America",
    source: "Live chat",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-01 15:00 CET",
    resolutionTarget: "2026-04-03 17:00 CET",
    firstResponse: "",
    lastUpdate: "2026-04-01 14:12 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Vida Clara Centro Medico",
    contact: "Ana Perez",
    email: "ana.perez@vidaclara.example",
    accountTier: "Standard",
    contractType: "Standard monthly plan",
    routingGroup: "General Support",
    approvalRequired: "No",
    approvalReason: "",
    description:
      "Customer wants to understand whether VAT labels in exported invoices can be renamed for a local market workflow.",
    internalNotes:
      "Useful sparse record to test missing owner and priority in both list and detail views.",
    emailThreadId: "",
    callReference: "",
    chatSessionId: "CHAT-SES-440901",
  },
  {
    ...INITIAL_CASE_RECORD,
    id: "CASE-10495",
    title: "Customer asked when suspended invoice reminders will resume after account verification",
    status: "Waiting on customer",
    priority: "Low",
    assignee: "Lucia Fernandez",
    queue: "Billing Communications",
    statusReason: "Waiting for the customer to confirm the compliance contact who should receive reminder emails.",
    onHoldUntil: "2026-04-05",
    channel: "Email",
    severity: "Minor",
    productArea: "Reminder Communications",
    category: "Notifications / Compliance recipient update",
    region: "Southern Europe",
    source: "Customer Support Mailbox",
    timelinePolicy: "Standard Support",
    responseTarget: "2026-04-01 13:30 CET",
    resolutionTarget: "2026-04-05 17:00 CET",
    firstResponse: "2026-04-01 13:02 CET",
    lastUpdate: "2026-04-01 13:44 CET",
    slaStatus: "On track",
    breachRisk: "Low",
    customer: "Viva la Vita Labs",
    contact: "Irene Costa",
    email: "irene.costa@vivalavitalabs.example",
    accountTier: "Professional",
    contractType: "Professional annual plan",
    routingGroup: "Billing Communications",
    description:
      "Customer needs confirmation on when automated reminders restart after updating the authorized reminder recipient.",
    internalNotes:
      "Hold until the customer confirms the compliance contact to avoid re-enabling reminders to the wrong mailbox.",
    emailThreadId: "THR-884302",
    callReference: "",
    chatSessionId: "",
  },
]

export const activityTimelineItems: ActivityTimelineItem[] = [
  {
    id: "activity-0",
    timestamp: "Apr 1, 2026, 08:54 CET",
    timestampDateTime: "2026-04-01T08:54:00+02:00",
    type: "incoming",
    actor: "Marta Ruiz",
    subtype: "Customer",
    organization: "Green Valley Clinic",
    content:
      "Hi, we're still unable to access the invoice portal after resetting the password twice. This is blocking our finance team. Could you take a look?",
  },
  {
    id: "activity-1",
    timestamp: "Apr 1, 2026, 09:07 CET",
    timestampDateTime: "2026-04-01T09:07:00+02:00",
    type: "comment",
    actor: "Lucia Fernandez",
    subtype: "Support operations",
    organization: "VivaLaVita",
    content:
      "Customer confirmed that invoice portal access still fails after two password resets and that the same issue affects the finance lead in the clinic group.",
  },
  {
    id: "activity-1b",
    timestamp: "Apr 1, 2026, 09:18 CET",
    timestampDateTime: "2026-04-01T09:18:00+02:00",
    type: "outgoing",
    actor: "Lucia Fernandez",
    subtype: "Support agent",
    organization: "VivaLaVita",
    content:
      "Hi Marta, thanks for reporting this. We’re currently investigating the issue with the invoice portal access. I’ll update you shortly once we confirm the root cause.",
  },
  {
    id: "activity-2",
    timestamp: "Apr 1, 2026, 09:26 CET",
    timestampDateTime: "2026-04-01T09:26:00+02:00",
    type: "status-change",
    actor: "Lucia Fernandez",
    subtype: "Support operations",
    organization: "VivaLaVita",
    content:
      "Case moved from New to In progress after support operations confirmed the incident is reproducible and requires account-state review.",
  },
  {
    id: "activity-3",
    timestamp: "Apr 1, 2026, 09:41 CET",
    timestampDateTime: "2026-04-01T09:41:00+02:00",
    type: "system",
    actor: "Auto-routing rule",
    subtype: "System",
    content:
      "Routing engine reassigned the case to Billing Portal Support because recent tenant-state signals matched the portal access recovery workflow.",
  },
  {
    id: "activity-4",
    timestamp: "Apr 1, 2026, 10:12 CET",
    timestampDateTime: "2026-04-01T10:12:00+02:00",
    type: "comment",
    actor: "Lucia Fernandez",
    subtype: "Internal note",
    organization: "VivaLaVita",
    content:
      "Internal note added to preserve current session logs and wait for identity-service confirmation before asking the customer to attempt another login.",
  },
]
